server:
    port: 9000
spring:
    datasource:
        password: "${MYSQL_PASSWORD}"
        url: "jdbc:mysql://localhost:3306/catsandhumans?useSSL=false"
        username: "${MYSQL_USERNAME}"
    jpa:
        hibernate:
            ddl-auto: "update"
credentials:
    admin:
        authorities: "ROLE_ADMIN"
        password: "admin"
        username: "admin"
    user:
        authorities: "ROLE_USER"
