server:
    port: 9000
spring:
    datasource:
        password: ${DB_PASSWORD}
        url: jdbc:mysql://localhost:3306/catsandhumans?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
