# Server configuration
server:
    port: 9000  # The port on which the server will run. Change this to adjust the server's listening port.

# Spring configuration
spring:
    datasource:
        # Database connection configuration (MySQL)
        username: "${MYSQL_USERNAME}"  # Database username, retrieved from environment variable MYSQL_USERNAME
        password: "${MYSQL_PASSWORD}"  # Database password, retrieved from environment variable MYSQL_PASSWORD
        url: "jdbc:mysql://localhost:3306/purrfect_database"  # Database URL, specifying the MySQL server location and database name

    # JPA (Java Persistence API) configuration, managing the interaction between Java application and the database.
    jpa:
        hibernate:
            ddl-auto: "update"  # Specifies the action taken for database schema management, "update" keeps the schema updated without losing data

    # configure backend to handle multipart/form-data requests by enabling multipart support in Spring Boot application
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

authorities:
    user: "ROLE_USER"
    admin: "ROLE_ADMIN"

logging:
    level:
        root: "INFO"  # Default logging level for all loggers
        purrfectMate: "DEBUG"  # Replace with your package; set to DEBUG to enable your own logs or OFF to disable them
        org:
            springframework:    # These are the relevant modules for our application context
            # security: "DEBUG"    # Use for debugging authentication and authorization issues.
            # web: "DEBUG"         # Use to debug request/response handling, especially for web endpoints.
            # http: "DEBUG"
            # data: "DEBUG"        # Use to monitor JPA repositories and database queries.
            # orm: "DEBUG"         # Use for debugging JPA/Hibernate entity management.
            # jdbc: "DEBUG"        # Use to see detailed SQL execution and database interactions.
            # core: "DEBUG"        # Use for general Spring functionality, bean processing.
            # context: "DEBUG"     # Use to debug application context initialization and bean management.